#!/usr/bin/env sh

#########
# Input #
#########

input() {
	printf "Search Torrent: " ; read -r name
	get_url
}

##################
# URL Processing #
##################

get_url() {
	search=$(echo "${name}" | sed 's/ /\%20/g')
	magnet=$(curl -s "$baseurl/search/${search}/1/99/200" | grep -Eo "magnet:\?xt=urn:btih:[a-zA-Z0-9]*" | head -n 1)
	choose
}


##########
# choice #
##########

stream() {
	peerflix -k "${magnet}"
}

download() {
	peerflix "${magnet}"
}

choose() {
	choice="$( printf "stream\ndownload" | fzf)"
	if [ "$choice" = "stream" ] ; then
		stream
	else
		download
	fi
}

###########
# Startup #
###########

# defaults 

baseurl=$(curl -s -L -o /dev/null -w "%{url_effective}\n" https://thepiratebay.party)
name=$(echo "$*") #| sed 's/ /\%20/g')

# checks if name variable is empty or not
[ -n "$name" ] && get_url
[ ! -n "$name" ] && input

