#!/usr/bin/env sh

#########
# Input #
#########

input() {
	printf "Search Torrent: " ; read -r name
	get_url
}

##################
# URL Processing #
##################

get_url() {
	search=$(echo "${name}" | sed 's/ /\%20/g')
	#curl -s "$baseurl/search/${search}" > "$HOME/.cache/url.html"
	magnet=$(curl -s "$baseurl/search/${search}" | grep -Eo "magnet:\?xt=urn:btih:[a-zA-Z0-9]*" | head -n 1)
	play
}


########
# Play #
########

play() {
	peerflix -l -k ${magnet}
}

###########
# Startup #
###########

# defaults 

baseurl="https://thepiratebay.party"
name=$(echo "$*" | sed 's/ /\%20/g')

# checks if name variable is empty or not

if [ ! -z "$name" ] ; then
	get_url
fi

if [ -z "$name" ] ; then 
	input
fi

